# Generated by Django 3.0.5 on 2020-04-18 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('term', models.CharField(choices=[('SPRING', 'Spring'), ('FALL', 'Fall')], max_length=32)),
                ('year', models.IntegerField()),
                ('entry_code', models.CharField(max_length=16)),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
