# Generated by Django 3.0.5 on 2020-05-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmain', '0004_auto_20200507_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='student',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lector',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
