# Generated by Django 3.0.5 on 2020-05-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmain', '0006_auto_20200507_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='entry_code',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.CharField(choices=[('SPRING', 'Spring'), ('FALL', 'Fall')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
