# Generated by Django 3.0.5 on 2020-05-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmain', '0005_auto_20200507_1957'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
